### PR TITLE
Fix #8

### LINKED ISSUE #8: Make stub constructor public instead of private
To avoid calling `setAccessible` it would be great to have stub constructors to be public.

https://github.com/vert-x3/vertx-grpc-java-compiler/blob/c197617dc7456da5647ad2c6b11e8a51e87b9f04/src/main/cpp/java_generator.cpp#L583

### PR DESCRIPTION
**Pull request by cescoffier**
Make the stub constructors public.

### CODE REVIEW

**Comment by vietj** [comment]
we should keep a list of the modifications we do so we can reapply them later, can we get that in a small .md file ?

**Comment by cescoffier** [comment]
I've added the changes to the README file.

**Comment by vietj** [comment]
shall we release it ?

**Comment by cescoffier** [comment]
I don't know the process, but +1 ;-)

**Comment by vietj** [comment]
`mvn deploy` is used (after `build.sh`)

what version shall it be ? `1.6.1.1` ? I remember we discussed that a while ago with @pmlopes

**Comment by pmlopes** [comment]
if we change the version to be different from upstream it might require more configuration for the end user as for now we just use the same `av` in project setup (g is our own `io.vertx`)

**Comment by vietj** [comment]
is it still needed @cescoffier ?

**Comment by cescoffier** [comment]
Yes, still needed.

**Comment by vietj** [comment]
can you rebase it on latest @pmlopes PR ?

**Comment by pmlopes** [comment]
Fixed by #11

**Comment by vietj** [comment]
thanks @pmlopes

**Pull request merged**
